#!/usr/bin/env bash
# a Bash script that configures the container to fit the above requirements

sed -i 's/user\s*root;/user nginx;/g' /etc/nginx/nginx.conf
sed -i 's/listen\s*\(.*\)\;$/listen 8080;/g' /etc/nginx/sites-available/defaultservice nginx restart
ps auxff | grep ngin[x]
nc -z 0 8080
